### ISSUE TITLE
能否提供下安装文件的下载地址

### ISSUE THREAD

**Issue by javaperson** [TencentOpen/behaviac#1]

**Comment by cainhuang** [comment]
你好，安装包也已经上传了，在https://github.com/TencentOpen/behaviac里面的“release”页面中。

发件人: 王阳 [mailto:notifications@github.com]
发送时间: 2015年4月14日 16:57
收件人: TencentOpen/behaviac
主题: [behaviac] 能否提供下安装文件的下载地址 (#1)(Internet mail)
