### ISSUE TITLE
在c#中如果与null值进行比较会check failed

### ISSUE THREAD

**Issue by JoeyMIao** [TencentOpen/behaviac#10]
在c#中如果 par或者变量与null值进行比较会check failed

**Comment by jonygli** [comment]
1. 这个需要更多的上下文信息才能回答你了。
2. null值应该只能是为了Agent或Agent的子类来工作的，如果用了其他非Agent类型的ref type的类会有问题的。
3. 这些问题再新版本中都已经有了处理，但新版本还需要时日才能上传。。。
4. 谢谢反馈。

**Comment by JoeyMIao** [comment]
好的 ，这个是我上个星期做demo时遇到的问题，晚点时候我会传更详细信息上来
