### ISSUE TITLE
Event事件触发模式选择转移，当子树行完之后，不能返回到先前的BT

### ISSUE THREAD

**Issue by JoeyMIao** [TencentOpen/behaviac#11]
Event事件触发模式选择”转移“，当子树行完之后，不能返回到先前的BT，而是一直不停的执行子树，在触发模式选择”返回“时则没有问题。

**Comment by jonygli** [comment]
是的，请阅读overview中相应的描述。

“触发模式”控制该事件触发后对当前 BT 的影响以及被触发的子树结束时如何恢复，有转移
（ Transfer）和返回（ Return）两个选项。
 转移 （ Transfer）：当前的 BT 被中断 (abort) 和重置 (reset)，新的 BT 被设置为当前 BT，
当这个新的 BT 结束的时候。
 返回 （ Return）：子树结束时返回控制到之前打断的地方继续执行。当前的 BT 直接‘压’
到执行堆栈上而不被 abort 和 reset，新的 BT 被设置为当前 BT，当这个新的 BT 结束的时候，原本的那个 BT 从执行堆栈上‘弹出’从当初的节点恢复执行。

**Comment by JoeyMIao** [comment]
"当这个新的 BT 结束的时候."这后面是不是没写完，当初看到这里的时候，我又参考了editor里面关于“转移”的说明“子树结束时返回控制，之前打断的行为树被重新执行”。我看了这段的理解是两种模式都会返回到之前被打断的行为树，只是“转移”是从之前的行为树重新开始执行，而“返回”是从之前的行为树打断的那个节点继续执行。

“转移”模式的定义是我理解错误了吗？是直接转移到子树，不在返回到之前的行为树了是吗？

**Comment by jonygli** [comment]
是的，谢谢你的反馈。后续更新下相关文档和说明！

**Comment by JoeyMIao** [comment]
好的，新版本期待中！

**Comment by jonygli** [comment]
除了fix bug外，新版本将有若干新的更加方便的features。如，在编辑器内将允许创建新的Agent类型等，Precondition，Effector将被支持，等等。

而且，新版本将会支持HTN。敬请期待。
