### ISSUE TITLE
请问是否有接入lua的计划？

### ISSUE THREAD

**Issue by puckery** [TencentOpen/behaviac#13]
现在游戏很多用lua来做开发，bt项目组是否有接入lua的计划？

**Comment by Aaron-Teng** [comment]
+1



aaron_teng@hotmail.com
 
发件人： Kugu
发送时间： 2015-07-08 16:13
收件人： TencentOpen/behaviac
主题： [behaviac] 请问是否有接入lua的计划？ (#13)
现在游戏很多用lua来做开发，bt项目组是否有接入lua的计划？

**Comment by jonygli** [comment]
呃，考虑过，应该也不是很麻烦。从解释器调用lua函数还是相当直接和方便的，lua脚本生成meta信息也不困难。但近期不会有时间实现了。

希望社区能够提供帮助咩。

**Comment by puckery** [comment]
两种方案：
1.完全用lua重写behavior的代码，数据接口一致；
2.导出c++ / c#的核心接口，lua来调用;

感觉第一种还容易些
