### ISSUE TITLE
请联系项目组索取

### ISSUE THREAD

**Issue by woopengcheng** [TencentOpen/behaviac#14]
想问下,现在里面说的安装包中的build目录中只包含了unittest的项目文件.完整项目文件,请和项目组联系.以及安装包中,designer未包含源码,从git下载下来的是都包含了的是么?安装包是什么呢?   另外,git下载的那个sapceship,跑了一晚上,貌似内存泄露了.

**Comment by raptoravis** [comment]
github是完整版本，包含了几乎所有东西，唯一没有包含的就是那个premake4，由于版权问题，请自行下载。

安装包里是编译好的lib，包含了所有源码，但未包含项目文件等，而且没有包含designer源码。

内存泄露的问题是在于debug/开发版本的问题。BEHAVAIC_RELEASE定义的话就不会有泄露了。

**Comment by jonygli** [comment]
github是完整版本，包含了几乎所有东西，唯一没有包含的就是那个premake4，由于版权问题，请自行下载。

安装包里是编译好的lib，包含了所有源码，但未包含项目文件等，而且没有包含designer源码。

内存泄露的问题是在于debug/开发版本的问题。BEHAVAIC_RELEASE定义的话就不会有泄露了。

**Comment by woopengcheng** [comment]
good!
