### ISSUE TITLE
object does not match target type

### ISSUE THREAD

**Issue by Tangoyzx** [TencentOpen/behaviac#15]
![image](https://cloud.githubusercontent.com/assets/6286936/8869009/a4c4f8d2-3211-11e5-8efd-3e5de715ad2e.png)
![image](https://cloud.githubusercontent.com/assets/6286936/8869015/b186ec88-3211-11e5-9b1f-a946adf77da7.png)
![image](https://cloud.githubusercontent.com/assets/6286936/8869029/d3c94aac-3211-11e5-85ef-5294d1b8ab8e.png)
![image](https://cloud.githubusercontent.com/assets/6286936/8869034/dea5d242-3211-11e5-989e-365c30fec4be.png)
为什么会报object does not match target type的错？

**Comment by jonygli** [comment]
"object does not match target type"是编辑器里报的错还是unity里报的错？

**Comment by Tangoyzx** [comment]
unity中报的错误

通过
behaviac.Agent.RegisterName<BTFacade>();
behaviac.Agent.BindInstance(btFacade);
![image](https://cloud.githubusercontent.com/assets/6286936/8869152/28a040f2-3213-11e5-8ceb-564aad1c6b97.png)

绑定了btFacade的类

BtEnemy就只有Init的时候加载btsetcurrent和Update的时候btexec了
character中init没有加载行为树，单纯地调用了Init

**Comment by jonygli** [comment]
有可能是这个bindinstance带来的问题。我们查下。你如果可以的话，可以暂时先不用bindinstance试试看。等我们fix了可以再改回来。谢谢反馈。

**Comment by Tangoyzx** [comment]
假如不用bindInstance的话，应该如何在编辑器中使用类似单例的Agent呢？

**Comment by jonygli** [comment]
不用bindInstance的话，目前就没办法使用类似Singleton了。

这个bug，我们争取下周一发个版本吧。

**Comment by Tangoyzx** [comment]
好的，谢谢你们的付出
这是个很好的工具
加油

**Comment by jonygli** [comment]
对了，这个bug我们应该已经fix了，你用的是最新版本（2.14）吗？运行编辑器可以看到版本号。

**Comment by Tangoyzx** [comment]
我用的应该是2.0.7，因为是从http://gad.qq.com/tool/detail?id=2这边下载的
那我更新一下吧！

**Comment by Tangoyzx** [comment]
更新后可以了，谢谢

**Comment by Tangoyzx** [comment]
放入项目以后还是有出现这个问题
![image](https://cloud.githubusercontent.com/assets/6286936/9107729/4b4e666c-3c5c-11e5-8dbc-83db1cd02597.png)
但是这次项目代码太深了没办法贴所有代码
出问题的是
![image](https://cloud.githubusercontent.com/assets/6286936/9107735/5ddb0a7e-3c5c-11e5-94b3-24ac1729fb68.png)
直接调用一个没有参数的方法，返回类型也导出了


还有就是有时候编辑器会很奇怪，在没有重新加载工作区的情况下有时候会缺失某些方法，如下图就缺失了我要用的CreateMyCharacter的方法
![image](https://cloud.githubusercontent.com/assets/6286936/9107810/d225c324-3c5c-11e5-8c88-ab3784c908d9.png)
然后不知道怎么在编辑器中乱点点又出来了
![image](https://cloud.githubusercontent.com/assets/6286936/9107838/05d676b4-3c5d-11e5-8cb2-88d73cf79287.png)


CreatureManager导出的元数据：
![image](https://cloud.githubusercontent.com/assets/6286936/9107953/94a0115c-3c5d-11e5-907e-82aefc8c8f80.png)

Unity版本5.1.0 f3
behaviac版本2.1.4

**Comment by jonygli** [comment]
BindInstance了吗？

**Comment by Tangoyzx** [comment]
BindInstance
之前是没有写字符串的，后面加了个Str组成一个字符串，也是一样的效果
![image](https://cloud.githubusercontent.com/assets/6286936/9111172/d03fa4f2-3c76-11e5-85cd-2a2d799b5f59.png)


报错堆栈：

TargetException: Object does not match target type.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:236)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
behaviac.CMethodBase.run (behaviac.Agent parent, behaviac.Agent pSelf, System.Object[] param_values) (at Assets/Scripts/Utils/behaviac/runtime/Base/Utils.cs:360)
behaviac.CMethodBase.run (behaviac.Agent parent, behaviac.Agent pSelf) (at Assets/Scripts/Utils/behaviac/runtime/Base/Utils.cs:353)
behaviac.CMethodBase.Invoke (behaviac.Agent pAgent) (at Assets/Scripts/Utils/behaviac/runtime/Base/Utils.cs:479)
behaviac.Action.Execute (behaviac.Agent pAgent, EBTStatus childStatus) (at Assets/Scripts/Utils/behaviac/runtime/BehaviorTree/Nodes/Actions/Action.cs:261)
behaviac.Action+ActionTask.update (behaviac.Agent pAgent, EBTStatus childStatus) (at Assets/Scripts/Utils/behaviac/runtime/BehaviorTree/Nodes/Actions/Action.cs:359)
behaviac.BehaviorTask.exec (behaviac.Agent pAgent) (at Assets/Scripts/Utils/behaviac/runtime/BehaviorTree/BehaviorTree_task.cs:194)
behaviac.Sequence+SequenceTask.update (behaviac.Agent pAgent, EBTStatus childStatus) (at Assets/Scripts/Utils/behaviac/runtime/BehaviorTree/Nodes/Composites/Sequence.cs:97)
behaviac.BehaviorTask.exec (behaviac.Agent pAgent) (at Assets/Scripts/Utils/behaviac/runtime/BehaviorTree/BehaviorTree_task.cs:194)
behaviac.SingeChildTask.update (behaviac.Agent pAgent, EBTStatus childStatus) (at Assets/Scripts/Utils/behaviac/runtime/BehaviorTree/BehaviorTree_task.cs:1292)
behaviac.BehaviorTreeTask.update (behaviac.Agent pAgent, EBTStatus childStatus) (at Assets/Scripts/Utils/behaviac/runtime/BehaviorTree/BehaviorTree_task.cs:1535)
behaviac.BehaviorTask.exec (behaviac.Agent pAgent) (at Assets/Scripts/Utils/behaviac/runtime/BehaviorTree/BehaviorTree_task.cs:194)
behaviac.Agent.btexec_ () (at Assets/Scripts/Utils/behaviac/runtime/Agent/Agent.cs:1389)
behaviac.Agent.btexec () (at Assets/Scripts/Utils/behaviac/runtime/Agent/Agent.cs:1448)
SceneProgressManager.Update () (at Assets/Scripts/Battle/Managers/SceneProgress/SceneProgressManager.cs:16)

Tree的AgentType是一个SceneProgressManager的类，
![image](https://cloud.githubusercontent.com/assets/6286936/9111162/aefdaafa-3c76-11e5-86fa-b47af96739d7.png)

**Comment by jonygli** [comment]
你可以设个断点在Utils.cs:479，看一下pParent和pAgent都是什么，我怀疑pParent有问题。

**Comment by Tangoyzx** [comment]
我把包括behaviac的runtime以及Workspace的配置和代码全部删掉，重新加入以及重新写behaviac相关的代码又可以了……
可能真的是某些地方设置错误了吧。

**Comment by jonygli** [comment]
你的这个问题，我基本可以确信是因为你用了旧的代码或数据导致的。

这也提醒了我们需要对格式和版本进行更加严格的验证。周末愉快！

**Comment by Tangoyzx** [comment]
不好意思麻烦了
