### ISSUE TITLE
2.1.4，时间节点一旦选择了const以外的方式再选择回const会令到文本框消失

### ISSUE THREAD

**Issue by Tangoyzx** [TencentOpen/behaviac#16]
初始状态：
![image](https://cloud.githubusercontent.com/assets/6286936/8899873/774e1480-346c-11e5-8eed-f39c7c7f5561.png)
随意改动类型：
![image](https://cloud.githubusercontent.com/assets/6286936/8899877/7c3aff26-346c-11e5-9f43-92c8c6712f30.png)
改回到const：
![image](https://cloud.githubusercontent.com/assets/6286936/8899888/8959dd4e-346c-11e5-963a-ccf5a41cc9e8.png)

选中其他节点后重新选择该时间节点也没用

**Comment by cainhuang** [comment]
的确是个bug，等下一个版本修复。如果急用该功能，可以删除该时间节点，然后重新拉一个新的时间节点并配置其const时间属性。
