### ISSUE TITLE
导出行为树路径中包含中文的问题

### ISSUE THREAD

**Issue by likaisqq** [TencentOpen/behaviac#17]
如果路径中包含中文的话，在SetWorkspaceSettings的时候会返回false，我应该怎么做？

**Comment by jonygli** [comment]
我记得我们编辑器里是不允许用中文路径作为workspace路径的。我稍等确认下。

但无论怎样，不要用中文路径！

**Comment by likaisqq** [comment]
使用中文路径确实不好，但是游戏给用户之后无法保证路径一定是全英文的，所以请帮我确认一下是不是确实不能用中文路径，谢谢。

**Comment by jonygli** [comment]
你exe可以在任何目录，那个目录或者其父目录是中文都是ok的。
但你传给SetWorkspaceSettings的那个路径不允许是中文。那个路径是“相对于”你的exe的。请注意那个是相对路径！

**Comment by likaisqq** [comment]
谢谢，明白了

**Comment by jonygli** [comment]
多些反馈，我们也将在编辑器中限制对中文的使用。本来应该是有限制过的，不知道为什么没起作用。。。

**Comment by likaisqq** [comment]
恩好的。还有一个很初级的问题，我都不好意思开新的issue了。

**Comment by likaisqq** [comment]
恩，还有一个很初级的问题，我都不好意思开新的issue了。就在这里问您吧，希望您能帮我一下。

就是动作结点调用的方法是字符串时，在方法中接收不到正常的结果。
比如我有一个方法是UseGoods(char* pGoodsName)，在行为树中的行为结点中使用这个方法，在参数那里写一个"water"，这样的话在UseGoods方法里接收不到正确的字符串，在导出的xml中的信息是：<property Method="Self.CBTPlayer::UseGoods(&quot;water&quot;)" />。当方法的参数不是char*时都没问题，是我使用的方法不对吗？

**Comment by jonygli** [comment]
字符串的使用确实会麻烦些，不要自谦:)

这个按说应该是支持和工作的，在unittest中应该也有测这个参数是字符串的测试的。具体到你这里，你可以打开导出的xml文件，看看导出的是否正确？

**Comment by likaisqq** [comment]
不好意思我上个回答里的xml中的信息好像因为带了xml标签被解析了，xml文件里有关这个调用的信息是：property Method="Self.CBTPlayer::UseGoods(&quot;water&quot;)"。这个是正确的吗？

**Comment by jonygli** [comment]
看起来不对。

你可以先创建个string的par，把需要的字符串赋给它，然后把那个par作为参数传给函数，可以试试。

我这里也在确认这个问题。

谢谢反馈。

**Comment by likaisqq** [comment]
再次不好意思，上个回答不知道怎么复制错了，对不起。应该是这个：property Method="Self.CBTPlayer::UseGoods(&quot;water&quot;)

**Comment by likaisqq** [comment]
我复制的是下面图片上的，结果浏览器给解析成冒号了，不好意思，请再次确认一下。
![qq 20150804172424](https://cloud.githubusercontent.com/assets/13638063/9057625/e840e8fe-3acd-11e5-8ca2-3d31e2bd947b.png)

**Comment by jonygli** [comment]
这个应该是对的！我反正也在确认，晚些给你反馈哈！

多谢。

**Comment by jonygli** [comment]
我确认过了，这个是支持的，不应该有问题的呀。

请确保使用最新版本，2.1.4
