### ISSUE TITLE
InvalidOperationException: out of sync

### ISSUE THREAD

**Issue by Tangoyzx** [TencentOpen/behaviac#18]
InvalidOperationException: out of sync
System.Collections.Generic.Dictionary`2+Enumerator[System.Int32,behaviac.Agent].VerifyState () (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:912)
System.Collections.Generic.Dictionary`2+Enumerator[System.Int32,behaviac.Agent].MoveNext () (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:835)
System.Collections.Generic.Dictionary`2+ValueCollection+Enumerator[System.Int32,behaviac.Agent].MoveNext () (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:1145)
behaviac.World.btexec_agents () (at Assets/Scripts/Utils/Behaviac/Agent/World.cs:188)
behaviac.World.btexec () (at Assets/Scripts/Utils/Behaviac/Agent/World.cs:162)
BattleBehaviacWorkspace.OnTickWorld () (at Assets/Scripts/Battle/Managers/Behaviac/BattleBehaviacWorkspace.cs:31)
FrameLoopManager.OnFixedTick () (at Assets/Scripts/Battle/Managers/FrameLoop/FrameLoopManager.cs:25)
BattleFacade.FixedUpdate () (at Assets/Scripts/Battle/Managers/BattleFacade.cs:36)

代码结构大概是
继承了World写了一个BattleBehaviacWorld，然后放在BattleBehaviacWorkspace中初始化，
场景流程控制是SceneProgress，是一个Agent
SceneProgress执行到某步的时候会生成一个敌人，也是一个Agent，会在Awake的时候btload和btsetcurrent

在Unity的FixedUpdate时会调用代码的FrameLoop
然后会调用World的btexec
这个时候World中的Agents还只有SceneProgress
所以遍历所有Agents的时候先执行SceneProgress的btexec
然后这一轮执行后SceneProgress会生成一个Agent
然后SceneProgress的btexec运行完以后遍历下一个Agent时报错

假如让Agent在Awake的时候不btload和btsetcurrent的话不会报错
或者把Agent的生成放在World.btexec之后也不会报错

是否在World.btexec过程中不允许生成新的Agents？
因为样例BattleCityDemo中虽然也有类似的操作，但是每个Agent的btexec并不是由World执行，而是由另外一个类管理执行的

**Comment by jonygli** [comment]
是的，在World.btexec过程中不允许生成新的Agents，否则，world中遍历agents的那个的foreach就会像你这里这样出现异常。请调整下顺序。

另外，其实在我新的版本中，我重构了相应的代码就不会有你这里的这个问题了。

**Comment by Tangoyzx** [comment]
那就是现在需要这边类似例子里面GameCommonLevel那样自己想方法保存并运行就好了是吧

然后还有个问题
一般经常都看到说foreach会有内存泄露
但是看了下BT内部实现也有些地方使用了foreach

使用foreach是否真的会有问题？

**Comment by jonygli** [comment]
是的。那是一种方法。

foreach是会导致GC ALLOC，但内部用到foreach的地方是在开发版本中也就是BEHAVIAC_RELEASE没有定义的时候的代码，所以也是没有问题的，因为在发布版本中BEHAVIAC_RELEASE是需要定义的。
