### ISSUE TITLE
你好，请问这个项目License是什么？

### ISSUE THREAD

**Issue by RonTang** [TencentOpen/behaviac#19]
Hello，please tell me  what is license of this project ?
MIT or Zlib or GPL and so on...

**Comment by cainhuang** [comment]
BSD 3-Clause License

**Comment by coneo** [comment]
这是比较宽泛的协议了，允许你修改源码、闭源、商用

**Comment by cainhuang** [comment]
是的，允许随便修改，只是发布的时候记得在自己软件的license文件中把我们提供的license也整合进去就好。

**Comment by RonTang** [comment]
好的，谢谢诸位。Thanks all.
