### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [TencentOpen/behaviac#2]
I would like to point out that identifiers like "[`_BASE_LIST_H_`](https://github.com/TencentOpen/behaviac/blob/4d7336863d89d6c79ba69dbaf25bfa4212846dec/inc/behaviac/base/core/container/list_t.h#L14)" and "[`_BEHAVIAC_STATE_H_`](https://github.com/TencentOpen/behaviac/blob/4d7336863d89d6c79ba69dbaf25bfa4212846dec/inc/behaviac/agent/state.h#L14)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jonygli** [comment]
thanks for the feedback!

**Comment by miloyip** [comment]
Underscore at the end of identifier is suggested by [Google C++ Style Guide](https://google-styleguide.googlecode.com/svn/trunk/cppguide.html#The__define_Guard). Its suggestion for naming of include guard is:
~~~
<PROJECT>_<PATH>_<FILE>_H_
~~~

**Comment by elfring** [comment]
How do you think about to make [your include guards](http://en.wikipedia.org/wiki/Include_guard#Difficulties "Consistency for include guards") not only standard-compliant but also really unique by appending [a kind of UUID](http://en.wikipedia.org/wiki/Universally_unique_identifier "universally unique identifier")?

**Comment by jonygli** [comment]
that is a good point however I am not sure if necessary to use such a UUID kind of thing.

thanks.
