### ISSUE TITLE
关于对32位的支持和GCC4.3下编译报错

### ISSUE THREAD

**Issue by BalckCat** [TencentOpen/behaviac#20]
问题：怎么没支持32位的？      
我看了下build里的linux下的makefile有debug32的选项，但具体的behaviac.make里没有对应的指令，然后我自己加了，并把-m64的编译项去掉，在32位的linux下编译好单元测试的，运行也全部通过，在GCC4.4交叉编译了arm架构的linux也可以，但在GCC4.3里就报错了：
../../inc/behaviac/base/swapbyte.h:94: error: integer constant is too large for 'long' type
有什么办法可以轻松点编译通过呢？

网上查资料说在长整型后面加上LL就可以了，但我想尽量不改里面的代码，以后升级也可以方便点。

**Comment by jonygli** [comment]
目前已经测试和项目中使用的是windows下是32位的，linux下是64位的。linux下的32位没有测试过。

你本地先那样改吧。我们后续也相应的改上。

make文件是因为它原本是premake统一生成的，linux下的make文件是在那个premake生成的gmake版本的基础上少量修改而成的。
