### ISSUE TITLE
prefabs在切换到中文语言后显示不了

### ISSUE THREAD

**Issue by coneo** [TencentOpen/behaviac#21]
之前是英文语言，有创建一个prefabs组件，在切换到中文语言后无法显示。但是重新切回英文语言又显示了

**Comment by cainhuang** [comment]
现在是根据中英文名字来创建和查找这个prefab目录的，所以英文版本创建的prefab，中文版找不到了。这是个bug，后面修复一下。

**Comment by coneo** [comment]
恩哈，这问题不大，项目开始统一一下语言就行了，不过最好还是作一下支持

**Comment by cainhuang** [comment]
等下一个版本一起修复
