### ISSUE TITLE
关于定义变量未使用的情况

### ISSUE THREAD

**Issue by coneo** [TencentOpen/behaviac#22]
环境是linux，由于之前项目对编译选项比较严格，开了警告当错误选项（-Werror）。但是在使用该库的时候有一些变量是定义而未使用的，不好集成到项目中

**Comment by jonygli** [comment]
一些已知的warning是通过-Wno-xxxx来关掉的，具体可以看behaviac.make。

另外，Debug下warning数应该是0的。你是不是Release下的warning？release下由于BEHAVIAC_ASSERT的关系是有warning的。

**Comment by coneo** [comment]
behaviac.make里确有Wno关闭了一些警告提示，编译behaviac运行库没问题。我是在引入到项目中的时候编译有提示的，提示信息：

**Comment by jonygli** [comment]
你要不现在你的make里添加-Wno-unused-local-typedefs 试试看，这个问题，我后续看看怎么在库里解决。

**Comment by coneo** [comment]
我在自己里项目里加了-Wno-unused-local-typedefs，OK的。这里，如果项目有包含behaviac库的头文件，那么就要遵循项目的规则了。

**Comment by jonygli** [comment]
好的，了解，我们在后续版本里处理下。
