### ISSUE TITLE
QQ交流群

### ISSUE THREAD

**Issue by coneo** [TencentOpen/behaviac#23]
抱歉，发这里了。看前面有同学提到通过邮件列表或者QQ群交流，新建了个behaviac的QQ交流群，天朝特色，各位大拿进来交流哈。群号：194515292

**Comment by jonygli** [comment]
邮件列表或者QQ群等类似的讨论组在考虑和筹备中，为了不引起不必要的混乱，目前先不采用。

**Comment by coneo** [comment]
OK，这个先保留，后面看情况了哈
