### ISSUE TITLE
链接错误： undefined reference to 'typeinfo for behaviac::Agent'

### ISSUE THREAD

**Issue by coneo** [TencentOpen/behaviac#24]
不清楚是不是我的编译选项不对，提示：
 undefined reference to 'typeinfo for behaviac::Agent'
编译环境：redhat 64bit， gcc 4.8.1
测试例子很简单，就如下：
class npc : public behaviac::Agent
{
};

int main()
{
   npc n;
}

编译命令：
g++ -Iinclude main.cpp -Llib -lbehaviac_debugstatic_linux_gmake -lpthread

**Comment by jonygli** [comment]
需要在你的项目的make里添加-fno-rtti

游戏编程中不需要rtti

**Comment by coneo** [comment]
我们这面用了RTTI，比如dynamic_cast，肿么办

**Comment by jonygli** [comment]
那就把库里的-fno-rtti关掉

**Comment by coneo** [comment]
OK了，感谢
