### ISSUE TITLE
ExportMetas引起core dump

### ISSUE THREAD

**Issue by coneo** [TencentOpen/behaviac#25]
环境：linux 64bit

core dump位置：
CXmlNode::saveToFile(IFile* file)中的
file->Write(out.c_str(), out.size());

堆栈信息：
0  CXmlNode::saveToFile(this=0x260ca80, file=0x933221) at xml.cpp:691
1 IXmlNode::setAttr(this=0x260ca80, key=0x933221 "version", value=0x93321d "2.0") at ixml.h:393
2 behaviac::Agent::ExportMetas(fileName=0x86eb48 "bt/meta/ai.xml") at agent.cpp:401
3 behaviac::Workspace::ExportMetas(fileName=0x86eb48 "bt/meta/ai.xml") at workspace.cpp:322 

这堆栈的层级关系我没看懂，为何setAttr会直接跳到saveToFile。VS下调试下来没有这样的堆栈。
在Linux下调试，也看不出问题。求解

**Comment by jonygli** [comment]
这个问题我这里暂时没有机会来重现和查看。

不过，可以确定的是在linux 64系统上确实是支持和运行的。

可以检查下文件路径，debug版本，加些log等先尝试下？

**Comment by cainhuang** [comment]
请确保你们的游戏项目make文件中所定义的宏跟behaviac组件需要的宏保持一致：
DEFINES   += -D_DEBUG -DDEBUG
