### ISSUE TITLE
Event 无法传递事件参数

### ISSUE THREAD

**Issue by liudequ** [TencentOpen/behaviac#26]
测试Event时，也出现了 #9  出现的无法触发的问题，但我是抛异常。
三个异常，看log是BehaviorTree_task . m_currentTask 为空。
事件添加到根节点可正常触发，切换BT。
响应事件的BT里有设置par,但选中事件附件时，无法把事件里的参数设置到响应事件的BT的参数里。

![event](https://cloud.githubusercontent.com/assets/4133010/9350694/670a3f6a-4685-11e5-9510-df3108959af5.png)

**Comment by jonygli** [comment]
![image](https://cloud.githubusercontent.com/assets/11328107/9350818/6815ec64-4686-11e5-88dd-73cfb53677fc.png)

**Comment by liudequ** [comment]
感谢回复。
par_event_param_int 这个参数是在响应的BT里设定的么？我选中事件附件时，只会显示我截图的那部分内容。
红色圈中的部分，我的理解是把事件里的参数赋给par项。响应BT中使用par项。对么？

**Comment by jonygli** [comment]
红色部分是当你选中事件的时候显示的。可以参考Help->Overview相关部分，有说明的。

你通过FireEvent触发改事件的时候可以传递参数，例如FireEvent("myEventName", paramInt, paramBool)，paramInt和paramBool是参数。对于上图的例子，par_event_param_int和par_event_param_bool是定义在被触发的bt里的par，而val_int和val_bool是声明事件myEventName时那个event原型的参数名字，在运行时改值分别是paramInt和paramBool，就像调用了一个函数那样，paramInt和paramBool传递给了par_event_param_int和par_event_param_bool。

**Comment by liudequ** [comment]
感谢回复。
2.1.4版本中，把响应BT拖到根节点后，点击事件附件，是不显示变量，也就是上图红色框里的内容，需要Ctrl+R 后才可显示。可能是个小bug。这就是我没显示出来的原因。

**Comment by jonygli** [comment]
好的，了解。
