### ISSUE TITLE
动作节点选择self::Method的时候有时候选不中想选的方法

### ISSUE THREAD

**Issue by Tangoyzx** [TencentOpen/behaviac#28]
大概意思是例如建立了一个动作节点
然后我想选择一个A方法
在下拉列表里面选择了A
结果整个编辑器界面闪一下，然后动作节点选中的方法变成了B
即使直接在self:Method后面直接输入A方法的字符串，回车以后也是一样闪了一下变成了B
重启编辑器无效，新建行为树也无效

但是前期还是没问题的，所有方法都能正常地添加行为节点
但不知道哪个时间点开始就突然有这个情况
只针对某几个方法
但是这几个方法以前也使用过

目前添加这些方法的行为节点就只能通过复制以前已经建立的那些方法的行为节点，然后粘贴过去

**Comment by cainhuang** [comment]
首先确保你用的是最新版本，如果还有问题，能否把整个工作区文件发我测试一下？

**Comment by Tangoyzx** [comment]
确定是2.1.4版本的
应该怎么发送文件？

**Comment by cainhuang** [comment]
请打包后发到我的邮箱：arcst@163.com

**Comment by cainhuang** [comment]
查了一下，知道什么原因了。主要是你有2个方法的显示名（也即displayname）同名了：
Name="SetAnimation" DisplayName="SetAnimation"
Name="ForceSetAnimation" DisplayName="SetAnimation"
修改方法：要么将ForceSetAnimation的DisplayName改为ForceSetAnimation，要么将DisplayName设为空字符串

**Comment by Tangoyzx** [comment]
哦，的确是这样……
犯这种低级错误不好意思……

**Comment by cainhuang** [comment]
跟我们的代码处理也有关系，Displayname是比较容易相同，主要是那个下拉列表是根据Displayname来加进去的，后面我们这边代码也改进一下
