### ISSUE TITLE
编辑器中使用compute节点，使用 int型不能正确使用操作符

### ISSUE THREAD

**Issue by chendezhao** [TencentOpen/behaviac#30]
![agent](https://cloud.githubusercontent.com/assets/9063833/9730682/b257b694-564a-11e5-8401-9f35b773fd70.png)
![compute](https://cloud.githubusercontent.com/assets/9063833/9730683/b25e6d68-564a-11e5-9e88-704645ed2090.png)

**Comment by chendezhao** [comment]
![compute1](https://cloud.githubusercontent.com/assets/9063833/9730696/d602039c-564a-11e5-88f9-87e23bba1745.png)

**Comment by chendezhao** [comment]
ship.xml中age和HP分别是signed long 和 unsigned int，
原例树种的par uint int float 可以正常显示

**Comment by jonygli** [comment]
好的，多谢反馈。

**Comment by chendezhao** [comment]
解决方法，在plugin.cs 的 m_type_mapping中添加成员
{"unsigned int"   ,  "uint"}
{"signed int"    ,   "int"}

**Comment by jonygli** [comment]
well done，感谢。

**Comment by cainhuang** [comment]
需要在Compute.cs文件中，将以下代码：
Type type = Plugin.GetTypeFromName(Plugin.GetNativeTypeName(this.Opl.NativeType));
改为：
Type type = Plugin.GetTypeFromName(Plugin.GetNativeTypeName(this.Opl.GetValueType()));
