### ISSUE TITLE
使用instance作为property时，owner会属于self

### ISSUE THREAD

**Issue by chendezhao** [TencentOpen/behaviac#34]
用注册实例里面的成员属性时，导出的行为树以Self开头
解决方法：在DesignerPropertyComboEnumEditor的 CreateEditor函数加入一个参数string valueType（参考DesignerParamComboEnumEditor的CreateEditor, 该参数为组合框中选中的值）
判断editor as DesignerPropertyEnumEditor ！= null 
&& valueType ！= kself && valueType ！= kPar && valueType ！= kConst
editor .GlobalType = valueType

**Comment by cainhuang** [comment]
多谢，我们会整合进去修复这个bug
