### ISSUE TITLE
SelectorProbability后跟的Weight节点par(self)列表为空

### ISSUE THREAD

**Issue by Just4F** [TencentOpen/behaviac#38]
同样属于DecoratorNode的Time可以正常选择
版本3.1.9最新
![2](https://cloud.githubusercontent.com/assets/10041229/11237068/7b5d6764-8e18-11e5-8b7c-651b649a41eb.png)
![weight](https://cloud.githubusercontent.com/assets/10041229/11237080/8eca490c-8e18-11e5-8090-1e2255572fb2.png)
![time](https://cloud.githubusercontent.com/assets/10041229/11237083/925c1b2c-8e18-11e5-9bda-083f763649d1.png)

另是否有QQ群或其他即时交流工具/社区可以交流behaviac的使用、bug和问题?

**Comment by cainhuang** [comment]
Weight节点只能选择int类型的par，但目前DecoratorTime的选择类型没有限制为int，算是个bug，我马上改一下，也只能选int类型的par。你上面的par_actorAtta*和par_probalili*两个par应该都不是int类型的，你需要添加一个int类型的par给Weight节点用

**Comment by cainhuang** [comment]
另外，交流平台目前主要放在http://gad.qq.com/tool/detail/2，可以在里面看看各种问题，也欢迎提出你的问题。

**Comment by Just4F** [comment]
我想使用在weight上的变量是个float..
项目紧张跟踪源码没跟踪到int这个限制.
这种隐性的限制如果可以的话也请说明一下(虽然文档一般会慢一步)  :)

主项目方没有考虑建立即时交流渠道吗?
一般来说组内成员一般问题直接就可以互助, 不会太打扰到主创方的.

**Comment by pjkui** [comment]
QQ group:433547396，欢迎加入

**Comment by cainhuang** [comment]
现在已有项目的代码都是基于int来做Weight节点的，现在换为float可能有一定风险。这个int目前应该足够用了吧？Weight选择的原理，就是几个Weight子节点的值，换算为0.0到1.0的小数区间来做选择的

**Comment by Just4F** [comment]
int应该够用啦.  只是我之前使用的时候没注意这个限制, 所以导致选择不到.
然后不选择RandomGenerator(使用默认)Check和导出会报warning哈.   我看代码里是使用默认Generator的没有问题
嗯当然这个不影响使用

**Comment by cainhuang** [comment]
默认Generator基本够用了，报Warning一般没事，只是提醒一下，但报Error就不会让你导出
