### ISSUE TITLE
sample spaceship 在2013无法编译通过

### ISSUE THREAD

**Issue by jiansihun** [TencentOpen/behaviac#4]
------ Build started: Project: spaceship, Configuration: DebugDLL Win32 ------
LINK : fatal error LNK1104: cannot open file 'behaviac_debugdll_win32_vs2010.lib'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

sample spaceship 在2013无法编译通过。

you should set the following parameters on the Property Pages of the project.

Working Directory : $(TargetDir)
Environment : PATH=..\example\spaceship\SDL2\lib\x86

已经按照该指导进行配置。开发环境是window7 。

**Comment by jonygli** [comment]
thanks for the feedback. 
however this is not a problem as such configure is a user config so that you can configure it in your own sln. 
and it can be referenced in the accompany readme.

**Comment by jiansihun** [comment]
运行时库：

2.1 到http://premake.bitbucket.org/download.html下载 premake-4.4-beta5-windows.zip，并将解压缩后的premake4.exe复制到build文件夹中

2.2 运行build文件夹中的premake.bat，生成相关的工程文件，这些工程文件用于编译生成behaviac的运行时库

自己回来补坑。这个步骤编译出static lib（behaviac_debugdll_win32_vs2010.lib）。就可以使用了。（微软的提示实在看不懂）

**Comment by jonygli** [comment]
well done。

由于版权问题，需要自己下载premake4.exe :)

所有这些操作在readme中有说明。

谢谢反馈。
