### ISSUE TITLE
没有提供vs2015的项目，vs2015无法编译。在mingw-64下也无法编译通过

### ISSUE THREAD

**Issue by wx** [TencentOpen/behaviac#44]

**Comment by jonygli** [comment]
在vs2015里打开vs2013的项目不可以吗？

mingw-64确实没有支持。如果有支持，欢迎PR。

**Comment by wx** [comment]
在vs2015里打开2013的项目，也无法编译。
可能是premake的问题。
用premake5的话能直接生成2015的项目。
不过现有的项目配置premake5运行报错
我用cmake配置了个项目，不过很简单，倒是都能生成了。
等做个更细致配置
