### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [TencentOpen/behaviac#45]
Would you like to [replace any double quotes](https://github.com/TencentOpen/behaviac/blob/9be3512e42f5d9f3d1445a24abf2d5b71d7dccdd/inc/behaviac/behaviac.h#L17 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by jonygli** [comment]
thanks for you information.

in my experience, angle brackets are usually for standard library headers, while double quotes are for user headers. so, it is unnecessary to change then, isn't?

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by jonygli** [comment]
that is interesting and a good point.

however, like here [replace any double quotes](https://github.com/TencentOpen/behaviac/blob/9be3512e42f5d9f3d1445a24abf2d5b71d7dccdd/inc/behaviac/behaviac.h#L17 "Check header file inclusion style"), all my headers are in behaviac directory to avoid possible conflict.

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
* Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
* Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?
