### ISSUE TITLE
spaceship 示例中framework/WorldState.h文件里的头文件找不到？

### ISSUE THREAD

**Issue by fangdenghui** [TencentOpen/behaviac#46]
WorldState.h头文件里包含了#include "behaviac/agent/agent.h"
和#include "behaviac/agent/registermacros.h"，但我没有看到这两个文件，为什么？

**Comment by pjkui** [comment]
这两个头文件在工程上级目录的inc/behaviac/agent/agent.h中。这个提供agent类的定义。另一个提供注册宏的定义。也在上级目录的inc/behaviac/agent/中

**Comment by fangdenghui** [comment]
**问题1**

    #include "behaviac/agent/agent.h"
应该是说文件在本工程`behaviac/agent`目录下，但真实文件却在工程外，是否进行了其他配置？如果是，说明一下**配置位置**吧

**问题2**
这 `两个文件` 是使用你们这个框架仅需的2个文件吗？是否`还需要`其他文件？如果需要，请告诉我需要哪些环境!使用的是 `C++语言，visual studio 2013`
非常感谢@pjkui

**Comment by cainhuang** [comment]
问题1：
这个include的目录是这样设置的了：首先找到组件的inc目录所在位置，然后在自己的VS项目设置窗口中打开Configuration Properties -> C/C++ -> General -> Additioal Include Directories设置behaviac组件的inc目录所在的路径。这样设置好之后，当然在代码中#include "behaviac/agent/agent.h"就可以找到了。

问题2：
除了上面include的2个文件，还可以只include一个文件就好，#include "behaviac/behaviac.h"，如果不够，看看编译错误就可以搜到某个类所在的文件，然后自己再include这个文件就好，一般情况#include "behaviac/behaviac.h"这个文件就够了。

另外，可以参考demo_running这个小项目入手。

**Comment by fangdenghui** [comment]
@cainhuang 非常感谢  :kissing_heart:
