### ISSUE TITLE
关于test/usertest工程main.cpp代码执行流程问题

### ISSUE THREAD

**Issue by fangdenghui** [TencentOpen/behaviac#47]
个人对这个工程的理解：我们在BTPlayer.h和BTPlayer.cpp中定义好Agent继承类，在main.cpp中头文件包含/behaviac/exported/behaviac_generated/behaviors/generated_behaviors.h使用已经编辑好的导出的行为树，也就是说在main.cpp中，我们是直接使用生成的行为树。使用的过程是先在main()函数注册使用，等运行完毕注册掉。现在有2个问题：
问题1：我们为什么还要在main()函数里导出元信息？这个工作不是在未导出行为树前完成的吗？为啥在使用导出的行为树时导出元信息
问题2：在注册Agent和销毁Agent的过程中,我们执行行为树，但看不出在哪执行的，唯一的代码片段是：
	while (i++ < iCount)
	{
		behaviac::Workspace::GetInstance()->Update();
	};

    clock_t finish = clock();

    if (iCount > 0)
    {
        float duration = (float)(finish - start) / CLOCKS_PER_SEC;

		cout << "format " << ffParam << " duration(seconds):" << duration << " RunCount:" << iCount << endl;
    }
行为树执行时间不是应该自身内部逻辑实现的吗？这段时间加的iCount是干什么的？

**Comment by pjkui** [comment]
执行行为树有两种方式，一种是：
```cpp
Agent* agent= new Agent();
agent->btexec();
```

如果有26个不同的agent。
```cpp
AgentA agenta=new AgentA();
AgentB agentb= new AgentB();
...
AgentZ agentz=new AgentZ();
//此处写了26行

//然后执行行为树
agenta->btexec();
agentb->btexec();
agentc->btexec();
...
agentz->btexec();
```

是不是感觉很累，如果简单，执行行为树用一句
```cpp
behaviac::Workspace::GetInstance()->Update();
```

看来你读代码很仔细，加油

**Comment by fangdenghui** [comment]
那个Update是指执行一次吗？加入while(i++<iCount)是执行iCount次吗？

**Comment by cainhuang** [comment]
对，Workspace::Update是把维护的所有agent实例都执行一次btexec方法，加入while(i++<iCount)是执行iCount次，测试一下执行iCount次的总时间。
在自己的游戏中，一般情况直接调用Workspace::Update就够了，这样所有的agent实例都可以被执行一遍。但也许需求不同，你的游戏可能需要某个agent实例一帧被执行多次，而另一个agent实例仅仅需要执行一次，有这样的需要，就不要调Workspace::Update，而是自己按需调agent->btexec方法。
