### ISSUE TITLE
使用behaviac，我的工程里面需要添加哪些包？

### ISSUE THREAD

**Issue by fangdenghui** [TencentOpen/behaviac#48]
我现在打算使用behaviac来定义behaviac::Agent的子类，我看了***test/demo_running***里的***BTPlayer***代码，发现需要导入你们的包，我把inc文件下的所有文件加入到工程里，如图为包：
![image](https://cloud.githubusercontent.com/assets/12146141/11562451/03a7bc2c-9a09-11e5-9a00-2fcc62161b6f.png)

然后我在类里添加
    
    #include"inc\behaviac\behaviac.h"
但是无法使用behaviac::Agent,到底应该如何使用？求大神解答
:pray:

**Comment by fangdenghui** [comment]
知道了，原来caihaung已给我解答过，现放在这供其他人学习
![image](https://cloud.githubusercontent.com/assets/12146141/11563227/d8543c3a-9a0d-11e5-8536-2495371b0163.png)

**Comment by pjkui** [comment]
那些只是引用我们的头文件，还有dll文件呢，也要指明好路径。

**Comment by coneo** [comment]
其实看看里面的文档就清除了

**Comment by jonygli** [comment]
http://tencentopen.github.io/behaviac/docs/zh/tutorials/cpp_include/
