### ISSUE TITLE
Designer的调试模式是不是不太稳定？

### ISSUE THREAD

**Issue by yangguosdxl** [TencentOpen/behaviac#5]
可以说这个BT编辑器是很不错的。调试模型是不是还很不稳定呢？调试用起来好像挺诡异的。首先没有找到单步运行的方式，然后是断点运行时，行为很怪，基本看不出运行规律。。。

**Comment by jonygli** [comment]
没有单步运行方式，因为“单步运行”在这里没有意义。可以设置断点。

运行时，黄色高亮的节点是处于运行状态的节点。此外，如果有子树的的时候，目前的处理可能还可以改善，这个可以关注后续版本。

不知道你这里所指的“行为很怪”，能否给出更多的说明？谢谢反馈！

**Comment by yangguosdxl** [comment]
我所说的单步，指的是一个节点一个节点的运行。因为这样才能知道在这一帧里，整个流程在各个节点里的运行状态。如果能把这一帧里运行过的节点，全部用一个种显眼的颜色标注出来，那没有单步也是可以。只知道当前处于运行状态的节点，就很难调试那种在一帧就运行完了的行为树（一帧结束后没有处于运行状态的节点）。

“行为很怪”：在断点后，点继续运行，发现不能运行到下一帧，而是又运行了一次本帧。

**Comment by yangguosdxl** [comment]
@jonygli 希望发起一个邮件列表或者QQ群之类。大家能更方便地交流：-）

**Comment by jonygli** [comment]
BT的运行情况以不同的边框颜色来显示不同的状态。灰色代表在该帧该节点有运行更新过，但在该帧内就结束了，即经历了从enter， running， exit。
这里的问题是背景也正好是灰色的，所以看不出来了，你可以把背景选成其他颜色应该就好了。

同时，边框颜色来显示不同的状态。所以也可以回答你单步的问题。

谢谢反馈。
