### ISSUE TITLE
动作节点中等待节点设置秒数问题

### ISSUE THREAD

**Issue by fangdenghui** [TencentOpen/behaviac#50]
我想使用一个变量设置秒数，这个变量为double型，我也注册了，但就是在编辑器时间设置上显示不出来，怎么回事？
如图为节点
![image](https://cloud.githubusercontent.com/assets/12146141/11718346/77377d44-9f90-11e5-8f51-e4270b4409a0.png)
如图选择const和self均无法显示：

![image](https://cloud.githubusercontent.com/assets/12146141/11718511/4d1b87fc-9f91-11e5-841c-c577d3b280d7.png)
定义的变量，设置为Public：

    double wait_time;

注册在这里：

    REGISTER_PROPERTY(wait_time);

**Comment by jonygli** [comment]
请选用float类型。

不支持类型的cast，必须是完全一样的类型。
