### ISSUE TITLE
如何在Agent中引用一个类的静态常量？

### ISSUE THREAD

**Issue by fangdenghui** [TencentOpen/behaviac#51]
我定义了一个类，里面全是静态常量：
在Data.h中使用
如：

    class Data
    {
        static const double strike_radius;
         static const double strike_angle;
         ...
         ...DECLARE_BEHAVIAC_STRUCT(Data);
    }

同时在Data.cpp中注册
  
    BEGIN_PROPERTIES_DESCRIPTION(Data)
    {
        CLASS_DISPLAYNAME(L"Data类");
        CLASS_DESC(L"存储数据");
        REGISTER_PROPERTY(strike_radius).DISPLAYNAME(L"打击距离");
        REGISTER_PROPERTY(strike_angle).DISPLAYNAME(L"打击角度");
    }
    END_PROPERTIES_DESCRIPTION()

在初始化时我对类进行了注册，不再列举。但是使用不了。
同时我也尝试在Agent中设置Data的实例data，在Agent中注册变量data，但是仍无法使用，如何才能使用？

**Comment by jonygli** [comment]
请使用static，而不是static const试试看呢.

**Comment by nighcate** [comment]
DECLARE_BEHAVIAC_STRUCT这个在文档中怎么没发现？？

**Comment by jonygli** [comment]
DECLARE_BEHAVIAC_STRUCT是在3.x中加的。
请使用最新版本。3.2.10。

[behaviac升级的步骤及注意事项](http://tencentopen.github.io/behaviac/docs/zh/articles/updatenotes/)
