### ISSUE TITLE
无法导出Xml文件

### ISSUE THREAD

**Issue by fangdenghui** [TencentOpen/behaviac#52]
无法导出xml文件，修改元数据位置老是弹出异常：
![image](https://cloud.githubusercontent.com/assets/12146141/11719889/cdea84d6-9f97-11e5-983f-dfc2ca753cbd.png)
以前都能正常导出，最近不知为何导不出了，只能导出如图文件：
![image](https://cloud.githubusercontent.com/assets/12146141/11719945/0bc2e50a-9f98-11e5-8ebb-dcbc7ea32ca3.png)

**Comment by cainhuang** [comment]
现在是无法导出所有的行为树xml文件了吗？把上面错误窗口中的“详细信息”点击一下，展开看看里面的内容

**Comment by fangdenghui** [comment]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.ComponentModel.Win32Exception: 参数错误。
   在 Ookii.Dialogs.NativeMethods.CreateItemFromParsingName(String path)
   在 Ookii.Dialogs.VistaFolderBrowserDialog.SetDialogProperties(IFileDialog dialog)
   在 Ookii.Dialogs.VistaFolderBrowserDialog.RunDialog(IntPtr hwndOwner)
   在 System.Windows.Forms.CommonDialog.ShowDialog(IWin32Window owner)
   在 Behaviac.Design.EditWorkspaceDialog.importXMLButton_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
BehaviacDesigner
    程序集版本: 3.2.8.0
    Win32 版本: 3.2.8
    基本代码: file:///C:/Program%20Files%20(x86)/behaviac/tools/designer/out/BehaviacDesigner.exe
----------------------------------------
BehaviacDesignerBase
    程序集版本: 1.0.0.0
    Win32 版本: 1.0.0.0
    基本代码: file:///C:/Program%20Files%20(x86)/behaviac/tools/designer/out/BehaviacDesignerBase.DLL
----------------------------------------
System.Windows.Forms
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5491 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5492 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5483 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
PluginBehaviac
    程序集版本: 1.0.0.0
    Win32 版本: 1.0.0.0
    基本代码: file:///C:/Program%20Files%20(x86)/behaviac/tools/designer/out/PluginBehaviac.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    程序集版本: 2.5.0.24386
    Win32 版本: 2.5.0.0
    基本代码: file:///C:/Program%20Files%20(x86)/behaviac/tools/designer/out/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
0e-shetb
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
BehaviacDesigner.resources
    程序集版本: 3.2.8.0
    Win32 版本: 3.2.8
    基本代码: file:///C:/Program%20Files%20(x86)/behaviac/tools/designer/out/zh-CN/BehaviacDesigner.resources.DLL
----------------------------------------
System.Windows.Forms.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.5420 (Win7SP1.050727-5400)
    基本代码: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_zh-CHS_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
BehaviacDesignerBase.resources
    程序集版本: 1.0.0.0
    Win32 版本: 1.0.0.0
    基本代码: file:///C:/Program%20Files%20(x86)/behaviac/tools/designer/out/zh-CN/BehaviacDesignerBase.resources.DLL
----------------------------------------
PluginBehaviac.resources
    程序集版本: 1.0.0.0
    Win32 版本: 1.0.0.0
    基本代码: file:///C:/Program%20Files%20(x86)/behaviac/tools/designer/out/zh-CN/PluginBehaviac.resources.DLL
----------------------------------------
XMLPluginBehaviac
    程序集版本: 0.0.0.0
    Win32 版本: 0.0.0.0
    基本代码: file:///C:/Users/fangdenghui/AppData/Local/Temp/Behaviac/XMLPluginBehaviac.dll
----------------------------------------
XMLPluginBehaviac
    程序集版本: 0.0.0.0
    Win32 版本: 0.0.0.0
    基本代码: file:///C:/Users/fangdenghui/AppData/Local/Temp/Behaviac/XMLPluginBehaviac.dll_0
----------------------------------------
XMLPluginBehaviac
    程序集版本: 0.0.0.0
    Win32 版本: 0.0.0.0
    基本代码: file:///C:/Users/fangdenghui/AppData/Local/Temp/Behaviac/XMLPluginBehaviac.dll_1
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如: 

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何无法处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

**Comment by cainhuang** [comment]
好，已经解决，在后面发布的3.2.9以上的新版本会修复该bug了
