### ISSUE TITLE
编译android版本失败

### ISSUE THREAD

**Issue by adangcc** [TencentOpen/behaviac#53]
3.2.8版本。
在编译android版本的时候，先运行premake.bat，然后修改android/build.bat里NDKBUILD的路径后运行。
出现 make: Circular obj/local/armeabi/libbehaviac.so <- obj/local/armeabi/libbehaviac
.so dependency dropped. 的错误，麻烦问下知道怎么处理吗？

**Comment by jonygli** [comment]
对的，会有编译错误，可以先把出错的那部分代码注释掉。正在fix中。

**Comment by jonygli** [comment]
请下载最新版本，已解决。
