### ISSUE TITLE
自定义枚举类型时，一个枚举的名字是另一个枚举的子集，用xml调试有问题。

### ISSUE THREAD

**Issue by nighcate** [TencentOpen/behaviac#54]
当我这样定义
enum EnumTest
{
    EnumTest_One = 0,
    EnumTest_OneAfterOne = 1,

};
并在Bt编辑器中这样使用
![image](https://cloud.githubusercontent.com/assets/7967507/11777612/76599716-a28a-11e5-9629-8782cf4926b1.png)

发现当我设置成员变量_enumTest为EnumTest_OneAfterOne 时，_enumTest == EnumTest_OneAfterOne这一句在编辑器中是False

vs2010， 32位，xml。
描述不清可以联系我~  QQ：928157563

**Comment by jonygli** [comment]
好的，多谢反馈，安排fix

**Comment by jonygli** [comment]
多谢反馈，确实是一个bug，fix会在下个版本里
