### ISSUE TITLE
在cocos2d下面如何使用这个东西

### ISSUE THREAD

**Issue by jiansihun** [TencentOpen/behaviac#6]
rt

**Comment by jonygli** [comment]
有项目接入过cocos2d，还是算方便的。

首先请参考Overview中“C++程序使用 behaviac”
然后如果还有问题，具体的可以参考Tutorial

可以打开编辑器在Help（帮助）菜单选择Overview（概述）或Tutorial（教程）来打开相应帮助。

谢谢反馈。

**Comment by jiansihun** [comment]
如果可以的话提供一个cocos2d接入教程。

**Comment by jiansihun** [comment]
花了时间看了sample的代码，回来补问题的坑。

GameLogic 中有逻辑帧代码step函数。其中有代码如下：

float dt = ws->timeElapsed / 1000.0f;
behaviac::Workspace::SetDeltaFrameTime(dt);
ws->btexec();

表明btexec函数按照AI需要按照逻辑帧更新。把这个代码写在cocos2d 的update中即可。

---------------------------------------------------------------------------------------------------------------------------------------

GameObject中有TurnTowardsTarget将飞机头部转向玩家控制飞机发射导弹。

其中GameObject中代码doAction为虚函数，在代码中就是一个意淫位置， 没有干嘛。
/*
		for (ConstGameObjectIter itr = objects->begin(); itr != objects->end(); ++itr)
		{
			GameObject* g = *itr;
			g->age += ws->timeElapsed;
			g->doActions(dt);
		}*/


---------------------------------------------------------------------------------------------------------------------------------------
暂时没有看懂projectileBrain这个干嘛用的。

**Comment by jonygli** [comment]
欢迎兄弟能够提供cocos2d的接入教程！让我们一起合力把behaviac做的更好用！

**Comment by jonygli** [comment]
最新版3.2.5中包含有cocos的demo。
http://tencentopen.github.io/behaviac/
