### ISSUE TITLE
请问C++版加载xml的时候只能通过提供xml文件地址的方式吗？

### ISSUE THREAD

**Issue by vectorguo** [TencentOpen/behaviac#60]
我们是使用C++开发，然后在unity里调用dll的方式来开发的。这种情况的话，如果打手机包的话，我们会把xml文件都打成assetbundle，这种情况就没办法提供xml文件的路径了，只有对应的bytes，这种情况怎么加载xml啊？

**Comment by jonygli** [comment]
可以重载FileManager来加载
