### ISSUE TITLE
当使用Event来注册BT子树时发生意外情况

### ISSUE THREAD

**Issue by JoeyMIao** [TencentOpen/behaviac#9]
首先是整个逻辑会开在附加了子树的节点（目前测试了两个一个是selector一个是sequence）走不下去,这个是从Designer链接到游戏的时候观察到的，然后还有就是整个事件无法正确触发。
![qq 20150527132438](https://cloud.githubusercontent.com/assets/9451142/7829375/bf366014-0473-11e5-9327-87b5d772050d.png)

事件的定义是
    [behaviac.EventMetaInfo("useCardEvent", "")]
    public delegate bool useCardEvent();

触发事件调用
FireEvent("useCardEvent")

unity3d 版本5.0.2

**Comment by jonygli** [comment]
谢谢反馈，已经发行了这个问题。在目前的版本中会有这个触发的问题。
你目前可以把这个事件移到根节点就可以了。

后续版本中会有fix。

**Comment by JoeyMIao** [comment]
It works! 谢谢
